### ISSUE TITLE
Update information on September, October

### ISSUE THREAD

**Issue by jhutchins** [davedelong/calendar_fallacies#18]
It would be interesting to add to the question on the numeric placement of the dates to add the the prefixes of September, October, November and December literally mean 7, 8, 9 and 10 respectively. https://en.m.wikipedia.org/wiki/Numeral_prefix

**Comment by davedelong** [comment]
Agreed! ;) http://yourcalendricalfallacyis.com/#it-is-normal-that-the-sept--oct--nov--and-dec--months-are-numbered-9-10-11-and-12
