### ISSUE TITLE
Leap years occur every four years contains incorrect example

### ISSUE THREAD

**Issue by paulymer** [davedelong/calendar_fallacies#2]
The fallacy "Leap years occur every four years" contains this text:

"False. The year 2000 was not a leap year."

2000 was a leap year in the Gregorian calendar. 1900 would be a better example.

**Comment by ZevEisenberg** [comment]
It might also be nice to mention the rule, or go deeper on how leap year works: every year that's divisible by 4, except years divisible by 100, except years divisible by 400, and then sprinkle around some leap seconds to taste.

**Comment by davedelong** [comment]
Fixed in f4c8478083bac7214eed5541fe30f6de7e82b468
