### ISSUE TITLE
Linkable fallacies

### ISSUE THREAD

**Issue by jorgelamb** [davedelong/calendar_fallacies#24]
It would be interesting to have each fallacy linkable / with an anchor so you can get a link to one specific fallacy.

**Comment by davedelong** [comment]
When I get some free time, I'd like to re-do the UI a bit so I can link directly to a single page for a fallacy, instead of just a point in the list, like how yourlogicalfallacyis.com works.

**Comment by davedelong** [comment]
Fallacies now have lines next to each header for easily copying an anchor URL.
