### ISSUE TITLE
Add Japanese year

### ISSUE THREAD

**Issue by nrooney** [davedelong/calendar_fallacies#29]
Japanese year follows the year of the current Emporer's reign:

http://www.japan-guide.com/e/e2272.html

Happy Heisei 29!

**Comment by kiliankoe** [comment]
I believe this to already be mentioned, see http://yourcalendricalfallacyis.com/#the-current-year-only-changes-at-new-years

**Comment by davedelong** [comment]
🙇 yep, I got this. Thanks! :)
