### ISSUE TITLE
Inconsistent title punctuation 

### ISSUE THREAD

**Issue by alvierahman90** [davedelong/calendar_fallacies#30]
Some headings don't have a period but others do
> Days don't last longer than 25 hours

> Everything you know about calendars is applicable to space travel. 

Some headings are a question but are missing a question mark
> It is normal that the Sept-, Oct-, Nov-, and Dec- months are numbered 9, 10, 11, and 12

**Comment by davedelong** [comment]
The "Sept-, Oct-, Nov-..." one is actually phrased correctly: "It is" (a statement) vs "Is it" (a question).
