### ISSUE TITLE
Someday we will be able to create a _perfect_ calendar that fixes all these problems.

### ISSUE THREAD

**Issue by churowa** [davedelong/calendar_fallacies#40]
Nope.

(This is yours, I just thought it'd be great to put up there.)

**Comment by kiliankoe** [comment]
Shouldn't there at least be some reasoning as to why it's supposedly impossible to create such a *perfect* calendar?

**Comment by churowa** [comment]
The reasoning is essentially that because of relativistic effects, you can never really create a system that *fully* encompasses what you'd need to describe the exact time at every point.

So for instance... the time you record depends on your velocity, right? So strictly speaking, someone who is running is moving through time more slowly than someone who is standing still. As a practical matter, this is irrelevant. But if you wanted to create a calendar that worked on Earth *and* in other parts of the solar system, you'd have trouble.

Having said that, this is probably too hyperbolic. I posted it more as a joke.
