### ISSUE TITLE
"Month lengths follow regular cycles" fallacy fallacy 😅

### ISSUE THREAD

**Issue by benmuta** [davedelong/calendar_fallacies#5]
Great work, thanks Dave!

I think I spotted a mistake:

In this fallacy you wrote:
_[...] and the moon isn’t visible, then the previous month just keeps going… and going…_

Actually the visibility only determines wether the month will be 29 days long. If the new moon is sighted, then the following day is the first of the next month, so the current month stops at 29. 

If it can't be seen, then the month is only one day longer, 30 days, and the day after the 30th is automatically the first day of the next month, without moon sight. 

Furthermore, a "previsional" long term calendar is often established in order to be able to deal with future dates. The 29/30 pendulum regularly merges back with the long term calendar. (Don't quote me on this last one, since there are many sources and differs by countries).

**Comment by davedelong** [comment]
Fantastic, thanks for the clarification!
