### ISSUE TITLE
Days are always sequential within a month

### ISSUE THREAD

**Issue by apechimp** [davedelong/calendar_fallacies#6]
That is there are no 'gaps' between days in a month.

In September 1752 (US), 10 days were removed (9/3-9/13) to switch from the Julian Calendar to the Gregoian Calendar. 

## See Also

https://en.wikipedia.org/wiki/Adoption_of_the_Gregorian_calendar
https://www.timeanddate.com/calendar/julian-gregorian-switch.html

**Comment by apechimp** [comment]
Apologies! This _is_ in the list! Great work!

**Comment by davedelong** [comment]
Yeah it is, but I just added the wikipedia link. thanks! :)
