### ISSUE TITLE
DST adjustments are always 1 hour

### ISSUE THREAD

**Issue by iaintatchbbc** [davedelong/calendar_fallacies#67]
False. During the Second World War, the United Kingdom adopted "Double British Summer Time" and put the clocks forward by two hours, in order to maximise available daylight hours (during the Blitz there was a blackout order preventing streetlights or car headlamps being used). It also coincidentally meant that the UK's clocks were synchronised with those of their allies (and enemies!) in Western Europe. Source http://www.bbc.co.uk/newsbeat/article/35890353/the-time-when-the-clocks-changed-by-more-than-an-hour, https://en.wikipedia.org/wiki/British_Summer_Time, and others.

**Comment by ajdlinux** [comment]
In Australia, Lord Howe Island only advances 30 minutes during DST, so DST isn't even necessarily aligned to an hour.

**Comment by davedelong** [comment]
This is awesome, thank you!  https://yourcalendricalfallacyis.com/#daylight-saving-time-adjustments-are-always-one-hour-forward-or-backward
