### ISSUE TITLE
Fallacy: Leap years happen every 4 years.

### ISSUE THREAD

**Issue by jacomyma** [davedelong/calendar_fallacies#89]

**Comment by jacomyma** [comment]
Then of course:
Fallacy: Leap years happen every 4 years *except every 100 years*.

**Comment by wsdwl** [comment]
Leap year rule:
•every 4 years
•except when the year is evenly divisible by 100
•unless it’s also evenly divisible by 400 (2000 was a leap year)

**Comment by gheja** [comment]
This is already on the site:
https://github.com/davedelong/calendar_fallacies/blob/master/fallacies.js#L129-L139

**Comment by davedelong** [comment]
Thanks! I've got this on the site.
